version: "2"
services:
  app:
    container_name: rewards-server-v1.0
    restart: always
    build: .
    ports:
      - "4001:4001"
    links:
      - mongo
  mongo:
    container_name: rewards-server-db
    image: mongo
    volumes:
      - /opt/db:/data/db
    expose:
      - "27017"
